"""Adding email_verified to user model

Revision ID: 430858baa2fb
Revises: 6e8ca4b1e897
Create Date: 2024-06-27 09:33:43.476222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430858baa2fb'
down_revision = '6e8ca4b1e897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
